ALTER TABLE `tmp`.`requirement` 
DROP FOREIGN KEY `REQUIREMENT_PROJECT_MAPPING`;
ALTER TABLE `tmp`.`requirement` 
ADD CONSTRAINT `REQUIREMENT_PROJECT_MAPPING`
  FOREIGN KEY (`PROJECT`)
  REFERENCES `tmp`.`project_mapping` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
  ALTER TABLE `tmp`.`requirement_profile_mapping` 
DROP FOREIGN KEY `REQUIREMENT_PROFILE_MAPPING_PROFILE`;
ALTER TABLE `tmp`.`requirement_profile_mapping` 
ADD CONSTRAINT `REQUIREMENT_PROFILE_MAPPING_PROFILE`
  FOREIGN KEY (`PROFILE_ID`)
  REFERENCES `tmp`.`profile` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  
  ALTER TABLE `tmp`.`requirement_profile_mapping` 
DROP FOREIGN KEY `REQUIREMENT_PROFILE_MAPPING_REQUIREMENT`;
ALTER TABLE `tmp`.`requirement_profile_mapping` 
ADD CONSTRAINT `REQUIREMENT_PROFILE_MAPPING_REQUIREMENT`
  FOREIGN KEY (`REQUIREMENT_ID`)
  REFERENCES `tmp`.`requirement` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
  ALTER TABLE `tmp`.`profile` 
CHANGE COLUMN `PROFILE_SHARED_CUSTOMER` `PROFILE_SHARED_CUSTOMER` VARCHAR(50) NULL DEFAULT NULL ;

ALTER TABLE `tmp`.`profile` 
CHANGE COLUMN `CURRENT_CTC` `CURRENT_CTC` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `EXPECTED_CTC` `EXPECTED_CTC` VARCHAR(50) NULL DEFAULT NULL ;

ALTER TABLE `tmp`.`requirement` 
CHANGE COLUMN `oppurtunity_Status` `OPPORTUNITY_STATUS` INT(11) NULL DEFAULT NULL ;


ALTER TABLE `tmp`.`requirement` 
ADD COLUMN `SKILL_CATEGORY2` VARCHAR(60) NULL AFTER `OPPORTUNITY_STATUS`,
ADD COLUMN `SKILL_CATEGORY3` VARCHAR(60) NULL AFTER `SKILL_CATEGORY2`,
ADD COLUMN `SKILL_CATEGORY4` VARCHAR(60) NULL AFTER `SKILL_CATEGORY3`;


ALTER TABLE REQUIREMENT
DROP FOREIGN KEY REQUIREMENT_PROFILE;


ALTER TABLE `tmp`.`REQUIREMENT` 
CHANGE COLUMN `SHORTLISTED_PROFILE_ID` `SHORTLISTED_PROFILE_ID` VARCHAR(100) NULL DEFAULT NULL 


ALTER TABLE `tmp`.`requirement` 
CHANGE COLUMN `IBG_CDG` `IBG_CDG` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `IBU_CDU` `IBU_CDU` INT(11) NULL DEFAULT NULL ;


ALTER TABLE `tmp`.`requirement` 
ADD INDEX `REQUIREMENT_IBG_idx` (`IBG_CDG` ASC);
ALTER TABLE `tmp`.`requirement` 
ADD CONSTRAINT `REQUIREMENT_IBG`
  FOREIGN KEY (`IBG_CDG`)
  REFERENCES `tmp`.`admin_info_key_value_mapping` (`ID`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

  
  ALTER TABLE `tmp`.`requirement` 
ADD INDEX `REQUIREMENT_IBU_idx` (`IBU_CDU` ASC);
ALTER TABLE `tmp`.`requirement` 
ADD CONSTRAINT `REQUIREMENT_IBU`
  FOREIGN KEY (`IBU_CDU`)
  REFERENCES `tmp`.`admin_info_key_value_mapping` (`ID`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE tmp.requirement
DROP COLUMN CUSTOMER_NAME;

ALTER TABLE `tmp`.`requirement_profile_mapping` 
DROP FOREIGN KEY `REQUIREMENT_CUSTOMER`;
ALTER TABLE `tmp`.`requirement_profile_mapping` 
ADD CONSTRAINT `REQUIREMENT_CUSTOMER`
  FOREIGN KEY (`CUSTOMER_INTERVIEW_STATUS`)
  REFERENCES `tmp`.`config_key_value_mapping` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  ALTER TABLE `tmp`.`requirement_profile_mapping` 
DROP FOREIGN KEY `REQUIREMENT_INTERNAL`;
ALTER TABLE `tmp`.`requirement_profile_mapping` 
ADD CONSTRAINT `REQUIREMENT_INTERNAL`
  FOREIGN KEY (`INTERNAL_EVALUATION_RESULT`)
  REFERENCES `tmp`.`config_key_value_mapping` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
